version = 1.0.0

minecraft_version=1.21.11
maven_group=net.teujaem

# 1.12.x ~ 1.16.x = 8
# 1.17.x = 16
# 1.18.x ~ 1.20.4 = 17
# 1.20.5+ = 21
java_version=21

#Fabric
fabric_version=0.141.3+1.21.11
#fabric_version=0.138.0+1.21.10
#fabric_version=0.119.4+1.21.4
#fabric_version=0.116.7+1.21.1
#fabric_version=0.92.6+1.20.1
org.gradle.jvmargs=-Xmx4G
loader_version=0.17.3

#Spigot 1.12 or 1.13
spigot_api_version=1.21

#velocity
velocity_version=3.4.0-SNAPSHOT